export const FETCH_USER = "FETCH_USER";
export const ADD_PROJECT = "ADD_PROJECT";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_SINGLE_PROJECT = "FETCH_SINGLE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
